[package]
name = "rgl"
version = "0.1.0"
authors = ["Stuart Harlan <stuart.harlan@modot.mo.gov>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindings = { path = "bindings" }
windows = "0.9"